[pytest]
testpaths = tests/integration tests/e2e
python_files = test_*.py
python_functions = test_*
python_classes = Test*
pythonpath = .
filterwarnings =
    ignore::DeprecationWarning:pkg_resources.*
markers =
    integration: mark a test as an integration test
    e2e: mark a test as an end-to-end test
    use_db_menu: mark a test to use the database for menu operations